### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by moas** [sdelrio/docker-minimal-nginx#1]
Hi!
I've this message when I run your image:
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)

**Comment by sdelrio** [comment]
Hi, that's not a real problem, since we change the error log to:

```
error_log /tmp/error.log;
```

On `nginx.non-root.conf` that would be on `/etc/nginx/nginx.conf`. You get that because we are runing on non-root user, so first time nginx starts try to write there by default, we change to `/tmp` so user `nobody`can write there.
